#    repoURL: 'https://github.com/akadmin-ai/trivia-gitops-demo.git'
 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivia-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/akadmin-ai/trivia-gitops-demo.git'
    targetRevision: HEAD
    path: trivia-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: trivia-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
