apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MicroService-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/akadmin-ai/aks-demo.git'
    targetRevision: HEAD
    path: app-chart-1
    helm:
      valueFiles:
         - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservice-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
