apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-1
  namespace: microservice-1
spec:
  project: microservice-1
  source:
    repoURL: 'https://github.com/KadirvelA/ocp-1.git'
    targetRevision: HEAD
    path: app-chart-1
    helm:
      valueFiles:
         - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservice-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
