apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-2
  namespace: microservice-2
spec:
  project: microservice-2
  source:
    repoURL: 'https://github.com/KadirvelA/ocp-1.git'
    targetRevision: HEAD
    path: app-chart-2
    helm:
      valueFiles:
         - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservice-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
