apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservice-2
  name: argocd-role
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: microservice-2
  name: argocd-rolebinding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
