apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: {{ .Values.appname }}
