apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: trivia
spec:
  type: LoadBalancer
  selector:
    app: trivia-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
