name: CI/CD Pipeline for Trivia App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker registry
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and Push Docker Image
      run: |
          docker build -t akadirvel1/trivia-frontend:${{ github.sha }} trivia-app/frontend
          docker push akadirvel1/trivia-frontend:${{ github.sha }}

    - name: Update Image Tag in Helm Chart
      run: |
          chart_dir="trivia-app/k8s"
          new_image_tag=${{ github.sha }}
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

    - name: Commit the changes made
      run: |
          git config --global user.name 'Kadirvel'
          git config --global user.email 'a.kadirvel@gmail.com'
          git add k8s/values.yaml

          # Ensure we're working with the main branch (or any relevant branch)
          git checkout main
      
          # Fetch latest changes from the remote repository
          git fetch origin
      
          # Force reset to match the remote branch, discarding local changes
          git reset --hard origin/main
      
          # Pull the latest changes to ensure everything is in sync
          git pull origin main
          # Commit and push changes if any are present
          git commit -am "Committing changes before pushing"
          git push origin main