name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List files to verify the directory structure
        run: |
          ls -R .  # List everything in the root directory to see if trivia-app exists
          ls -R trivia-app  # List the contents of trivia-app
          ls -R trivia-app/backend  # List the contents of backend

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./trivia-app/Dockerfile
          push: true
          tags: akadirvel1/trivia-app:latest
          no-cache: true
